import React,{useState} from 'react';
import Select from 'react-select';

export const Multipledropdown = () => {
    var multiplevalues =[
        {
            value:1,
            label:"algol 59"
        },
        {
            value:2,
            label:"algol 58",
        },
        {
            value:3,
            label:"algol 60",
        },
        {
            value:4,
            label:"BCPL"
        },
        {
            value:5,
            label:"BETA",
        },
        {
            value:6,
            label:"BASIC",
        },
        {
            value:7,
            label:"CSS",
        },
        {
            value:8,
            label:"C#",
        },
        {
            value:9,
            label:"C",
        },
        {
            value:10,
            label:"Data Structure",
        },
        {
            value:11,
            label:"DCL",
        },
        {
            value:12,
            label:"Embeded",
        },
        {
            value:13,
            label:"E",
        },
        {
            value:14,
            label:"Factor",
        },
        {
            value:15,
            label:"Flex",
        },
        {
            value:16,
            label:"GO",
        },
        {
            value:17,
            label:"G-code",
        },
        {
            value:18,
            label:"HTML",
        },
        {
            value:19,
            label:"HTML5",
        },
        {
            value:20,
            label:"HLSL",
        },
        {
            value:21,
            label:"Inform",
        },
        {
            value:22,
            label:"IOT",
        },
        {
            value:23,
            label:"JAVA",
        },
        {
            value:24,
            label:"JAVASCRIPT",
        },
        {
            value:25,
            label:"KRL",
        },
        {
            value:26,
            label:"KRC",
        },
        {
            value:27,
            label:"ML",
        },
        {
            value:28,
            label:"MAD",
        },
        {
            value:29,
            label:"Neko",
        },
        {
            value:30,
            label:"Newspeak",
        },
        {
            value:31,
            label:"OOPS",
        },
        {
            value:32,
            label:"Oak",
        },
        {
            value:33,
            label:"PPL",
        },
        {
            value:34,
            label:"PHP",
        },
        {
            value:35,
            label:"P4",
        },
        {
            value:36,
            label:"Q",
        },
        {
            value:37,
            label:"Quakec",
        },
        {
            value:38,
            label:"QtScript",
        },
        {
            value:39,
            label:"Rubay",
        },
        {
            value:40,
            label:"R",
        },
        {
            value:41,
            label:"R++",
        },
        {
            value:42,
            label:"S",
        },
        {
            value:43,
            label:"SQL",
        },
        {
            value:44,
            label:"S2",
        },
        {
            value:45,
            label:"S3",
        },
        {
            value:46,
            label:"TACL",
        },
        {
            value:47,
            label:"TACPOL",
        },
        {
            value:48,
            label:"TACL",
        },
        {
            value:49,
            label:"TACL",
        },
        {
            value:50,
            label:"Unicon",
        },
        {
            value:51,
            label:"Ubercode",
        },
        {
            value:52,
            label:"vue js",
        },
        {
            value:53,
            label:"Vim script",
        },
        {
            value:54,
            label:"Visual Dataflex",
        },
        {
            value:55,
            label:"WebDNA",
        },
        {
            value:56,
            label:"Whiley",
        },
        {
            value:57,
            label:"Winbatch",
        },
        {
            value:58,
            label:"Wolfram Language ",
        },
        {
            value:59,
            label:"WebAssembly",
        },
        {
            value:60,
            label:"XPL",
        },
        {
            value:61,
            label:"XPLO",
        },
        {
            value:62,
            label:"XBL",
        },
        {
            value:63,
            label:"XC",
        },
        {
            value:64,
            label:"X++",
        },
        {
            value:65,
            label:"X10",
        },
        {
            value:66,
            label:"Yorick",
        },
        {
            value:67,
            label:"YQL",
        },
        {
            value:68,
            label:"Yoix",
        },
        {
            value:69,
            label:"Z notation",
        },
        {
            value:70,
            label:"ZPL",
        },
        {
            value:71,
            label:"ZPL2",
        },
        {
            value:72,
            label:"Z shell"
        }
    ];
const [Display, getvalue] = useState([])
    const handleChange= (e)=>{
        getvalue(Array.isArray(e)?e.map(x=>x.label):[]);
    }
    return (
        <div>
           <Select isMulti options={multiplevalues} onChange={(e)=>{handleChange(e)}}></Select> 
          <center><b>Selected Values:</b><h3 style={{color:"yellowgreen"}}>{Display}</h3></center>
        </div>
    )
}
export default Multipledropdown